### ISSUE TITLE
Question (not issue)

### ISSUE THREAD

**Issue by criswit** [sjakthol/aws-kms-crypt#1]
Hi there

I wanted to ask a quick question on this repo you have put together - should it be able to handle encryption of large files ? Meaning not just the encryption of the data key, but also encrypt a 10GB data file (for example) as well?

Thanks for any info

**Comment by sjakthol** [comment]
The utility uses OpenSSL to decrypt / encrypt the data. I'm not aware of any size limits OpenSSL would have on the size of the data to encrypt / decrypt.

However, the library has been designed to encrypt small snippets of data. There are three issues that arise if you try to encrypt large blobs:

1. The encrypted data is base64 encoded. If you encrypt 10GB file, the output will need a lot of extra space (4/3 * original i.e. 13.3GB in the case of 10GB input).
2. The plaintext / encrypted blob is read to memory before encryption / decryption occurs. Hence, you need a lot of RAM to e.g. encrypt 10 GB file (at least 10GB to read in the original and the 13 GB for output plus most likely there's a lot of overhead for node and python at least).
3. Performance is likely to be poor due to JSON parsing / encoding process.

While there are no hard limits that would limit the size of the data, I cannot recommend using this tool for that purpose.
